% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name first
%  @associatedFile /MATLAB Drive/first.m
%  @mostRecentlyActioned true
%  @uniqueId 2E9AD123

first

%% @name tut1q4
%  @associatedFile /MATLAB Drive/tut1q4.m
%  @mostRecentlyActioned true
%  @uniqueId AE61CD8F

tut1q4

%% @name tut1q6
%  @associatedFile /MATLAB Drive/tut1q6.m
%  @mostRecentlyActioned true
%  @uniqueId 36C7B7BB

tut1q6

%% @name tut1q8b
%  @associatedFile /MATLAB Drive/tut1q8b.m
%  @mostRecentlyActioned true
%  @uniqueId 1419B4C7

tut1q8b

%% @name tut1q7
%  @associatedFile /MATLAB Drive/tut1q7.m
%  @mostRecentlyActioned true
%  @uniqueId BEE46FDF

tut1q7

%% @name tut1q9
%  @associatedFile /MATLAB Drive/tut1q9.m
%  @mostRecentlyActioned true
%  @uniqueId 82567B0E

tut1q9

%% @name tut1q12
%  @associatedFile /MATLAB Drive/tut1q12.m
%  @mostRecentlyActioned true
%  @uniqueId D1BDC28B

tut1q12

%% @name tut2q2
%  @associatedFile /MATLAB Drive/tut2q2.m
%  @mostRecentlyActioned true
%  @uniqueId 17407B05

tut2q2

%% @name tut2q9
%  @associatedFile /MATLAB Drive/tut2q9.m
%  @mostRecentlyActioned true
%  @uniqueId CC47DDF1

tut2q9

%% @name tut2q9b
%  @associatedFile /MATLAB Drive/tut2q9b.m
%  @mostRecentlyActioned true
%  @uniqueId F65930F2

tut2q9b

%% @name tut2q10
%  @associatedFile /MATLAB Drive/tut2q10.m
%  @mostRecentlyActioned true
%  @uniqueId AAF4D748

tut2q10

%% @name tut3q1
%  @associatedFile /MATLAB Drive/tut3q1.m
%  @mostRecentlyActioned true
%  @uniqueId 88A7CDC2

tut3q1

%% @name tut3q2
%  @associatedFile /MATLAB Drive/tut3q2.m
%  @mostRecentlyActioned true
%  @uniqueId 13C2CF94

tut3q2

%% @name tut3q6
%  @associatedFile /MATLAB Drive/tut3q6.m
%  @mostRecentlyActioned true
%  @uniqueId 773A82BB

tut3q6

%% @name ass3q3
%  @associatedFile /MATLAB Drive/ass3q3.m
%  @mostRecentlyActioned true
%  @uniqueId 6C48815E

ass3q3

%% @name ass3q4
%  @associatedFile /MATLAB Drive/ass3q4.m
%  @mostRecentlyActioned true
%  @uniqueId FFE7C2C0

ass3q4

